CONVERSION_JOB_SCHEMA_VERSION = "1.4.0"
CHAPTER_METADATA_SCHEMA_VERSION = "1.4.0"
GENERATE_CHUNKS_JOB_SCHEMA_VERSION = "1.1.0"
GENERATE_DOCX_JOB_SCHEMA_VERSION = "1.0.0"
SEMANTIC_CHUNKS_ARTIFACT_SCHEMA_VERSION = "2.0.0"
SEMANTIC_CHUNKS_MANIFEST_SCHEMA_VERSION = "2.0.0"
DOCX_MANIFEST_SCHEMA_VERSION = "1.0.0"
DOCX_FORMATTING_CONTRACT_VERSION = "1.0.0"
DOCX_TITLE_TEMPLATE_ID = "title-slug-prabodhan-chapter"
DOCX_TITLE_TEMPLATE_VERSION = "1.0.0"

PIPELINE_LEGACY_DOCX_TO_UNICODE = "legacy-docx-to-unicode"
PIPELINE_UNICODE_DOCX_INGEST = "unicode-docx-ingest"
PIPELINE_GENERATE_CHUNKS = "generate-chunks"
PIPELINE_GENERATE_DOCX = "generate-docx"

ENTRY_POINT_PREP_SUBJECT = "python3 -m gurubodh prep-subject"
ENTRY_POINT_LEGACY_DOCX_TO_UNICODE = "python3 -m gurubodh legacy-convert"
ENTRY_POINT_UNICODE_DOCX_INGEST = "python3 -m gurubodh unicode-ingest"
ENTRY_POINT_GENERATE_CHUNKS = "python3 -m gurubodh generate-chunks"
ENTRY_POINT_GENERATE_DOCX = "python3 -m gurubodh generate-docx"
ENTRY_POINT_LAB_PROOFREAD = "python3 -m gurubodh lab proofread"
SEMANTIC_CHUNKS_OUTPUT_DIR = "semantic_chunks"
DOCX_OUTPUT_DIR = "msword"

PIPELINE_ENTRY_POINTS = {
    PIPELINE_LEGACY_DOCX_TO_UNICODE: ENTRY_POINT_LEGACY_DOCX_TO_UNICODE,
    PIPELINE_UNICODE_DOCX_INGEST: ENTRY_POINT_UNICODE_DOCX_INGEST,
}

SUPPORTED_LEGACY_ENCODINGS = {"aps", "shreelipi"}
SUPPORTED_FONT_ENCODINGS = SUPPORTED_LEGACY_ENCODINGS | {"unicode"}
