CONVERSION_JOB_SCHEMA_VERSION = "1.2.0"
CHAPTER_METADATA_SCHEMA_VERSION = "1.2.0"
GENERATE_CHUNKS_JOB_SCHEMA_VERSION = "1.0.0"
SEMANTIC_CHUNKS_ARTIFACT_SCHEMA_VERSION = "1.0.0"
GENERATE_CHUNKS_SUMMARY_SCHEMA_VERSION = "1.0.0"

PIPELINE_LEGACY_DOCX_TO_UNICODE = "legacy-docx-to-unicode"
PIPELINE_UNICODE_DOCX_INGEST = "unicode-docx-ingest"
PIPELINE_GENERATE_CHUNKS = "generate-chunks"

ENTRY_POINT_PREP_SUBJECT = "python3 -m gurubodh prep-subject"
ENTRY_POINT_LEGACY_DOCX_TO_UNICODE = "python3 -m gurubodh legacy-convert"
ENTRY_POINT_UNICODE_DOCX_INGEST = "python3 -m gurubodh unicode-ingest"
ENTRY_POINT_GENERATE_CHUNKS = "python3 -m gurubodh generate-chunks"
SEMANTIC_CHUNKS_OUTPUT_DIR = "semantic_chunks_and_embeddings"

PIPELINE_ENTRY_POINTS = {
    PIPELINE_LEGACY_DOCX_TO_UNICODE: ENTRY_POINT_LEGACY_DOCX_TO_UNICODE,
    PIPELINE_UNICODE_DOCX_INGEST: ENTRY_POINT_UNICODE_DOCX_INGEST,
}

SUPPORTED_LEGACY_ENCODINGS = {"aps", "shreelipi"}
SUPPORTED_FONT_ENCODINGS = SUPPORTED_LEGACY_ENCODINGS | {"unicode"}
