CONVERSION_JOB_SCHEMA_VERSION = "1.2.0"
CHAPTER_METADATA_SCHEMA_VERSION = "1.2.0"

PIPELINE_LEGACY_DOCX_TO_UNICODE = "legacy-docx-to-unicode"
PIPELINE_UNICODE_DOCX_INGEST = "unicode-docx-ingest"

ENTRY_POINT_PREP_SUBJECT = "python3 -m gurubodh prep-subject"
ENTRY_POINT_LEGACY_DOCX_TO_UNICODE = "python3 -m gurubodh legacy-convert"
ENTRY_POINT_UNICODE_DOCX_INGEST = "python3 -m gurubodh unicode-ingest"

PIPELINE_ENTRY_POINTS = {
    PIPELINE_LEGACY_DOCX_TO_UNICODE: ENTRY_POINT_LEGACY_DOCX_TO_UNICODE,
    PIPELINE_UNICODE_DOCX_INGEST: ENTRY_POINT_UNICODE_DOCX_INGEST,
}

SUPPORTED_LEGACY_ENCODINGS = {"aps", "shreelipi"}
SUPPORTED_FONT_ENCODINGS = SUPPORTED_LEGACY_ENCODINGS | {"unicode"}

